config/routes.rb
Rails.application.routes.draw do

  get '/buy_shoe',to: 'buy#index'
  get '/buy_purse',to: 'buy#index1'
  get '/buy_hood',to: 'buy#index2'
  get '/buy_hood1',to: 'buy#index3'
  get 'homelogged_in/index'
  get 'detail_logged/index'
  get '/detail_no_login', to: 'detail_no_login#index'
  get '/detail_no_login2', to: 'detail_no_login#index2'
  get '/detail_no_login3', to: 'detail_no_login#index3'
  get '/detail_no_login4', to: 'detail_no_login#index4'
  get '/detail_logged', to: 'detail_logged#index'
  get '/detail_logged2', to: 'detail_logged#index2'
  get '/detail_logged3', to: 'detail_logged#index3'
  get '/detail_logged4', to: 'detail_logged#index4'
  get '/welcome', to: 'welcome#index'
  get '/homelogged_in', to: 'homelogged_in#index'
  get '/register', to: 'register#index'



  resources :orders

  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/home',  to: 'users#home'
  get '/about', to: 'users#about'
  get '/userorder', to: 'orders#userorder'
  get '/neworder', to: 'orders#new'
  get '/neworderfalse', to: 'sessions#new'
  root 'users#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :email, presence: true, uniqueness: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<div class="container-register">
    <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), home_path  %>
        </div>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <% if current_user %>
        <% else %>
        <div class="site-nav-3">
            <%= link_to "Sign Up", signup_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Log In", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "About" , about_path %>
        </div>
        <% end %>
        <% if current_user%>
        <% if current_user.email == 'admin'%>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
             <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Admin Order", orders_path %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% else %>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "User Order", userorder_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% end %>
        <% end %>
    </div>
    <div class="site-register">
        <div>
            <%= form_with(model: user, local: true) do |form| %>
            <% if user.errors.any? %>
            <div id="error_explanation">
                <h2>
                    <%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
                <ul>
                    <% user.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                    <% end %>
                </ul>
            </div>
            <% end %>
            <center>
                <h1>Editing User</h1>
                <div class="field">
                    <%= form.label :email %>
                    <%= form.text_field :email %>
                </div>
                <div class="field">
                    <%= form.label :password %>
                    <%= form.password_field :password %>
                </div>
                <div class="field">
                    <%= form.label :Password_Confirmation %>
                    <%= form.password_field :Password_Confirmation %>
                </div>
                <div class="actions">
                    <%=  form.submit %>
                </div>
                <% end %>
                <center>
        </div>
    </div>
    <div class="site-login-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </div>
</div>

app/views/users/_form.html.erb
<div class="site-main">
    <div>
        <%= form_with(model: user, local: true) do |form| %>
        <% if user.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
                <% user.errors.full_messages.each do |message| %>
                <li>
                    <%= message %>
                </li>
                <% end %>
            </ul>
        </div>
        <% end %>
        <center>
            <h1>Register</h1>
            <div class="field">
                <%= form.label :email %>
                <%= form.text_field :email %>
            </div>
            <div class="field">
                <%= form.label :password %>
                <%= form.password_field :password %>
            </div>
            <div class="field">
                <%= form.label :Password_Confirmation %>
                <%= form.password_field :Password_Confirmation %>
            </div>
            <div class="actions">
                <%=  form.submit %>
            </div>
            <% end %>
        </center>
    </div>
</div>

app/views/users/about.html.erb
<div class="container-about">
    <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), home_path  %>
        </div>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <% if current_user %>
        <% else %>
        <div class="site-nav-3">
            <%= link_to "Sign Up", signup_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Log In", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "About" , about_path %>
        </div>
        <% end %>
        <% if current_user%>
        <% if current_user.email == 'admin'%>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Edit", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Admin Order", orders_path %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% else %>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "User Order", userorder_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% end %>
        <% end %>
    </div>
    <div class="site-about link-color">
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Team Member</p>
            </header>
            <article>
                <p style="text-align: center;"><b>Auttaphol Thongvicit 5810613256</b></p>
                <p style="text-align: center;"><b>Tuchdech Jirabunyadech 5910613248</b></p>
                <p style="text-align: center;"><b>Boonyanut Puingyamsual 5910613305</b></p>
                <p style="text-align: center;"><b>Kittikun Kittithammo 5910613321</b></p>
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Proposal</p>
            </header>
            <article>
                <center>
                    <table cellspacing="20">
                        <tr>
                            <td><img src="images/pro1.png" width="350px" height="350px"></td>
                            <td><img src="images/pro2.png" width="350px" height="350px"></td>
                        </tr>
                        <tr>
                            <td><img src="images/pro3.png" width="350px" height="350px"></td>
                            <td><img src="images/pro4.png" width="350px" height="350px"></td>
                        </tr>
                    </table>
                </center>
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">User Stories</p>
            </header>
            <article>
                <center>
                    <table cellspacing="20">
                        <tr>
                            <td><img src="images/story1.png" width="400px" height="300px"></td>
                            <td><img src="images/story2.png" width="400px" height="300px"></td>
                        </tr>
                        <tr>
                            <td><img src="images/story3.png" width="400px" height="300px"></td>
                            <td><img src="images/story4.png" width="400px" height="300px"></td>
                        </tr>
                        <tr>
                            <td><img src="images/story5.png" width="400px" height="300px"></td>
                            <td><img src="images/story6.png" width="400px" height="300px"></td>
                        </tr>
                        <tr>
                            <td> <img src="images/story7.png" width="400px" height="300px"></td>
                            <td> <img src="images/story8.png" width="400px" height="300px"></td>
                        </tr>
                    </table>
                </center>
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Gitlab Repository Link</p>
            </header>
            <article>
                <center>
                    <p style="font-size: 1.2em"><a href="https://gitlab.com/5910613248/24preorder.git">https://gitlab.com/5910613248/24preorder.git</a></p>
                </center>
            </article>
        </div>
        <div>
            <header>
                <p style="font-size:2em;text-align: center;color:orange">Pivotal Tracker Link</p>
            </header>
            <article>
                <center>
                    <p style="font-size: 1.2em"><a href="https://www.pivotaltracker.com/projects/2407283">https://www.pivotaltracker.com/projects/2407283</a></p>
                </center>
            </article>
        </div>
    </div>
    <div class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </div>
</div>

app/views/users/edit.html.erb
<%= render 'edit_form', user: @user %>

app/views/users/home.html.erb
<div class="container-welcome">
    <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), home_path  %>
        </div>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <% if current_user %>
        <% else %>
        <div class="site-nav-3">
            <%= link_to "Sign Up", signup_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Log In", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "About" , about_path %>
        </div>
        <% end %>
        <% if current_user%>
        <% if current_user.email == 'admin'%>
         <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
             <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Admin Order", orders_path %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% else %>
         <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "User Order", userorder_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% end %>
        <% end %>
    </div>
    <div class="site-images-1">
        <div class="detailimag1">
            <%= link_to image_tag("nike-image3.jpg") , detail_no_login_path %>
        </div>
    </div>
    <!-- End Images Content 1 -->
    <div class="content1">
        <p style="font-size: 2.5em;">เสื้อผ้า และ Accessory มากมายมาแล้ววันนี้</p>
        <p>24 preorder คือร้านที่รวบรวมเสื้อผ้าและเครื่องแต่งกายที่เหมาะกับคุณ เพื่อสร้างประสบการณ์ที่แปลกใหม่ที่ไม่เคยมีที่ไหนมาก่อน พร้อมทั้งเรายังมีระบบ Search engine ที่สามารถ ค้นหาสินค้าที่คุณต้องการได้อย่างรวดเร็ว</p>
    </div>
    <!-- Start Images Content 2 -->
    <div class="site-images-2">
        <div class="detailimag2">
            <p style="font-size: 2.5em;">มาดูสินค้ากันเลยดีกว่า</p>
            <%= link_to image_tag("gucci1.jpg"), detail_no_login2_path %>
        </div>
    </div>
    <!-- End Images Content 2 -->
    <div class="content2">
        <p style="font-size: 2.5em;">กระเป๋า Gucci GG Marmont</p>
        <p>เป็นกระเป๋าที่เหมาะกัยคุณผู้หญิง ที่มีขนาด Dimenions: 9.5"W x 5"H x 3"D. Strap 23.5" ไม่ใหญ่เกินไปเหมาะกับการสะพายไปทำงาน</p>
    </div>
    <!-- Start Images Content 3 -->
    <div class="image3">
        <div class="site-images-3">
            <div class="site-images-3-left">
                <%= link_to image_tag("hood1.jpg",width:'600',height:'600'), detail_no_login3_path %>
            </div>
            <div class="site-images-3-right">
                <%= link_to image_tag("hood3.jpg",width:'600',height:'600'), detail_no_login4_path %>
            </div>
        </div>
    </div>
    <!-- End Images Content 3 -->
    <div class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container-register">
   <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), home_path  %>
        </div>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <% if current_user %>
        <% else %>
        <div class="site-nav-3">
            <%= link_to "Sign Up", signup_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Log In", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "About" , about_path %>
        </div>
        <% end %>
        <% if current_user%>
        <% if current_user.email == 'admin'%>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Admin Order", orders_path %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% else %>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "User Order", userorder_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% end %>
        <% end %>
    </div>
    <div class="site-register">
        <%= render 'form', user: @user %>
    </div>
    <div class="site-register-footer">
        <p style="text-align: center;">&copy; 2019 - CN340 SOFTWARE ENGINEERING</p>
    </div>

app/views/users/show.html.erb
    <div class="site-main">
        <div>
            <p id="notice"><%= notice %></p>

            <p>
              <strong>Email:</strong>
              <%= @user.email %>
            </p>
            
            <%= link_to 'Edit', edit_user_path(@user) %> |
            <%= link_to 'Back', root_path %>
            
        </div>
    </div>