config/routes.rb
Rails.application.routes.draw do

  get '/buy_shoe',to: 'buy#index'
  get '/buy_purse',to: 'buy#index1'
  get '/buy_hood',to: 'buy#index2'
  get '/buy_hood1',to: 'buy#index3'
  get 'homelogged_in/index'
  get 'detail_logged/index'
  get '/detail_no_login', to: 'detail_no_login#index'
  get '/detail_no_login2', to: 'detail_no_login#index2'
  get '/detail_no_login3', to: 'detail_no_login#index3'
  get '/detail_no_login4', to: 'detail_no_login#index4'
  get '/detail_logged', to: 'detail_logged#index'
  get '/detail_logged2', to: 'detail_logged#index2'
  get '/detail_logged3', to: 'detail_logged#index3'
  get '/detail_logged4', to: 'detail_logged#index4'
  get '/welcome', to: 'welcome#index'
  get '/homelogged_in', to: 'homelogged_in#index'
  get '/register', to: 'register#index'



  resources :orders

  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/home',  to: 'users#home'
  get '/about', to: 'users#about'
  get '/userorder', to: 'orders#userorder'
  get '/neworder', to: 'orders#new'
  get '/neworderfalse', to: 'sessions#new'
  root 'users#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    validates :name, presence: true
    validates :productname, presence: true
    validates :address, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def userorder
    @orders = Order.where(:name => current_user.email)
  end

  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :shoename, :address)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :shoename %>
    <%= form.text_field :shoename %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div class="container-register">
    <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), home_path  %>
        </div>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <% if current_user %>
        <% else %>
        <div class="site-nav-3">
            <%= link_to "Sign Up", signup_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Log In", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "About" , about_path %>
        </div>
        <% end %>
        <% if current_user%>
        <% if current_user.email == 'admin'%>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Admin Order", orders_path %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% else %>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "User Order", userorder_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% end %>
        <% end %>
    </div>
    <div class="site-register">
        <h1>Orders</h1>
        <table cellspacing="40">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Shoename</th>
                    <th>Address</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
                <% @orders.each do |order| %>
                <tr>
                    <td>
                        <%= order.name %>
                    </td>
                    <td>
                        <%= order.shoename %>
                    </td>
                    <td>
                        <%= order.address %>
                    </td>
                    <td>
                        <%= link_to 'Show', order %>
                    </td>
                    <td>
                        <%= link_to 'Edit', edit_order_path(order) %>
                    </td>
                    <td>
                        <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="site-login-footer">
        <p style="text-align: center;">&copy; 2019 - CN340 SOFTWARE ENGINEERING</p>
    </div>
</div>

app/views/orders/new.html.erb
<div class="container-buy">
    <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), home_path  %>
        </div>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <% if current_user %>
        <% else %>
        <div class="site-nav-3">
            <%= link_to "Sign Up", signup_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Log In", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "About" , about_path %>
        </div>
        <% end %>
        <% if current_user%>
        <% if current_user.email == 'admin'%>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Admin Order", orders_path %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% else %>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "User Order", userorder_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% end %>
        <% end %>
    </div>
    <div class="site-buy-form">
        <div class="site-payment-message">
            <p style="font-size:1.5em;">Select your payment method</p>
        </div>
        <div class="visa-logo">
            <%= radio_button_tag('credit-card','flase') %>
            <%= image_tag("visa-logo.png" , width:'80',height:'50')%>
        </div>
        <div class="mastercard-logo">
            <%= radio_button_tag('credit-card','flase') %>
            <%= image_tag("mastercard-logo.png" , width:'80',height:'50')%>
        </div>
        <div class="americanex-logo">
            <%= radio_button_tag('credit-card','flase') %>
            <%= image_tag("americanex-logo.png" , width:'80',height:'50')%>
        </div>
        <div class="paypal-logo">
            <%= radio_button_tag('credit-card','flase') %>
            <%= image_tag("paypal-logo.jpg" , width:'80',height:'50')%>
        </div>
        <div class="site-payment-method">
            <%= text_field_tag('text-card-no',nil , maxlength:16, placeholder:'Card Number') %>
            <%= text_field_tag('cvv',nil , maxlength:3 , size:5 , placeholder:'CVV') %>
            <%= render 'form', order: @order %>
        </div>
    </div>
    <div class="site-buy-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </div>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Shoename:</strong>
  <%= @order.shoename %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/userorder.html.erb
<div class="container-register">
    <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), home_path  %>
        </div>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <% if current_user %>
        <% else %>
        <div class="site-nav-3">
            <%= link_to "Sign Up", signup_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Log In", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "About" , about_path %>
        </div>
        <% end %>
        <% if current_user%>
        <% if current_user.email == 'admin'%>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Admin Order", orders_path %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% else %>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "User Order", userorder_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% end %>
        <% end %>
    </div>
    <div class="site-register">
        <h1>Your Orders</h1>
        <table cellspacing="40">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Shoename</th>
                    <th>Address</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
                <% @orders.each do |order| %>
                <tr>
                    <td>
                        <%= order.name %>
                    </td>
                    <td>
                        <%= order.shoename %>
                    </td>
                    <td>
                        <%= order.address %>
                    </td>
                    <td>
                        <%= link_to 'Show', order %>
                    </td>
                    <td>
                        <%= link_to 'Edit', edit_order_path(order) %>
                    </td>
                    <td>
                        <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="site-login-footer">
        <p style="text-align: center;">&copy; 2019 - CN340 SOFTWARE ENGINEERING</p>
    </div>
</div>