config/routes.rb
Rails.application.routes.draw do

  get '/buy_shoe',to: 'buy#index'
  get '/buy_purse',to: 'buy#index1'
  get '/buy_hood',to: 'buy#index2'
  get '/buy_hood1',to: 'buy#index3'
  get 'homelogged_in/index'
  get 'detail_logged/index'
  get '/detail_no_login', to: 'detail_no_login#index'
  get '/detail_no_login2', to: 'detail_no_login#index2'
  get '/detail_no_login3', to: 'detail_no_login#index3'
  get '/detail_no_login4', to: 'detail_no_login#index4'
  get '/detail_logged', to: 'detail_logged#index'
  get '/detail_logged2', to: 'detail_logged#index2'
  get '/detail_logged3', to: 'detail_logged#index3'
  get '/detail_logged4', to: 'detail_logged#index4'
  get '/welcome', to: 'welcome#index'
  get '/homelogged_in', to: 'homelogged_in#index'
  get '/register', to: 'register#index'



  resources :orders

  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/home',  to: 'users#home'
  get '/about', to: 'users#about'
  get '/userorder', to: 'orders#userorder'
  get '/neworder', to: 'orders#new'
  get '/neworderfalse', to: 'sessions#new'
  root 'users#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homelogged_in_controller.rb
class HomeloggedInController < ApplicationController
  def index
  end
end

app/views/homelogged_in/index.html.erb
<!-- Start Container-->
<div class="container-welcome">

    <!-- Start Header -->
    <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), welcome_path  %>
        </div>
        <div class="site-nav-1">
            <%= link_to "Home", welcome_path %>
        </div>
        <div class="site-nav-2">
            <a href="#">Store</a>
        </div>
        <div class="site-nav-3">
            <%= link_to "Login", login_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "About", about_path %>
        </div>
    </div>
    <!-- End Header -->

    <!-- Start Images Content 1 -->
    <div class="site-images-1">
        <div class="detailimag1">
        <%= link_to "Detail on login", detail_no_login_path %><br>
        <%= link_to "Go to buy", buy_path %><br>
        </div>
        <%= image_tag("nike-image3.jpg")%>

    </div>
    <!-- End Images Content 1 -->
    <div class="content1">
        <p class="bigger">Lorem Ipsum is simply dummy text.</p>
        <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type</p>
    </div>
    <!-- Start Images Content 2 -->
    <div class="site-images-2">
        <%= link_to "Detail on login", detail_no_login2_path %><br>
        <%= image_tag("gucci1.jpg")%><br>
    </div>
    <!-- End Images Content 2 -->
    <div class="content2">
        <p class = "bigger">it to make a type specimen book.</p>
        <p>t has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
    </div>

    <!-- Start Images Content 3 -->
    <div class="image3">
    <div class="site-images-3">
        <div class="site-images-3-left">
        <%= link_to "Detail on login", detail_no_login3_path %><br>
        <%= image_tag("hood1.jpg",width:'600',height:'600')%>
        </div>
    <div class="site-images-3-right">
        <%= link_to "Detail on login", detail_no_login4_path %><br>
        <%= image_tag("hood3.jpg",width:'600',height:'600')%>
        </div>
    </div>
</div>
    <!-- End Images Content 3 -->

    <!-- Start Footer -->
    <div class="site-footer">
        <p style="text-align: center;">&copy; 2019 - CN340 SOFTWARE ENGINEERING</p>
    </div>
    <!-- End Footer -->
</div>
<!-- End Container-->