config/routes.rb
Rails.application.routes.draw do

  get '/buy_shoe',to: 'buy#index'
  get '/buy_purse',to: 'buy#index1'
  get '/buy_hood',to: 'buy#index2'
  get '/buy_hood1',to: 'buy#index3'
  get 'homelogged_in/index'
  get 'detail_logged/index'
  get '/detail_no_login', to: 'detail_no_login#index'
  get '/detail_no_login2', to: 'detail_no_login#index2'
  get '/detail_no_login3', to: 'detail_no_login#index3'
  get '/detail_no_login4', to: 'detail_no_login#index4'
  get '/detail_logged', to: 'detail_logged#index'
  get '/detail_logged2', to: 'detail_logged#index2'
  get '/detail_logged3', to: 'detail_logged#index3'
  get '/detail_logged4', to: 'detail_logged#index4'
  get '/welcome', to: 'welcome#index'
  get '/homelogged_in', to: 'homelogged_in#index'
  get '/register', to: 'register#index'



  resources :orders

  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get '/home',  to: 'users#home'
  get '/about', to: 'users#about'
  get '/userorder', to: 'orders#userorder'
  get '/neworder', to: 'orders#new'
  get '/neworderfalse', to: 'sessions#new'
  root 'users#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/detail_no_login_controller.rb
class DetailNoLoginController < ApplicationController
  def index
  end
end

app/views/detail_no_login/index.html.erb
<!-- Start Container-->
<div class="container-detail-no-login">
    <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), home_path  %>
        </div>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <% if current_user %>
        <% else %>
        <div class="site-nav-3">
            <%= link_to "Sign Up", signup_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Log In", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "About" , about_path %>
        </div>
        <% end %>
        <% if current_user%>
        <% if current_user.email == 'admin'%>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Edit", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Admin Order", orders_path %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% else %>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "User Order", userorder_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% end %>
        <% end %>
    </div>
    <!-- Start Images Content 1 -->
    <div class="site-images-1">
        <%= image_tag("nike-image3.jpg")%>
    </div>
    <!-- End Images Content 1 -->
    <!-- Start detail -->
    <div class="detail link-color">
        <p style="font-size: 2em">Air Max 90 panelled sneakers</p>
        <p style="font-size: 1.5em">Grey Air Max 90 panelled sneakers from Nike featuring a signature Nike swoosh to the side, a logo patch at the tongue, a branded heel counter, a round toe, contrasting panels, a lace-up front fastening and a ridged rubber sole. Supplied by a premier sneaker marketplace dealing with unworn, already sold out, in demand rarities. Each product is rigorously inspected by experienced experts guaranteeing authenticity</p>
        <% if current_user %>
        <%= link_to ">> Buy Now <<" , neworder_path %>
        <% else %>
        <%= link_to ">> Buy Now <<" , neworderfalse_path %>
        <% end %>
    </div>
    <!-- End detail -->
    <div class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </div>
</div>
<!-- End Container-->

app/views/detail_no_login/index2.html.erb
<!-- Start Container-->
<div class="container-detail-no-login">
    <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), home_path  %>
        </div>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <% if current_user %>
        <% else %>
        <div class="site-nav-3">
            <%= link_to "Sign Up", signup_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Log In", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "About" , about_path %>
        </div>
        <% end %>
        <% if current_user%>
        <% if current_user.email == 'admin'%>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Edit", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Admin Order", orders_path %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% else %>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "User Order", userorder_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% end %>
        <% end %>
    </div>
    <!-- Start Images Content 1 -->
    <div class="site-images-1">
        <%=  image_tag("gucci1.jpg")%>
       
    </div>
    <!-- End Images Content 1 -->
    <!-- Start detail -->
    <div class="detail link-color">
        
        <p style="font-size: 2em">Gucci GG Marmont velvet small </p>
        <p style="font-size: 1.5em">shoulder bag- Dimenions: 9.5"W x 5"H x 3"D. Strap 23.5" drop. Black 'GG Marmont' quilted shoulder bag from Gucci. Metal logo at front. adjustable chain and leather shoulder strap, Made inItaly.</p>
        <% if current_user %>
        <%= link_to ">> Buy Now <<" , neworder_path %>
        <% else %>
        <%= link_to ">> Buy Now <<" , neworderfalse_path %>
        <% end %>
    </div>
    <!-- End detail -->
    <div class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </div>
</div>
<!-- End Container-->

app/views/detail_no_login/index3.html.erb
<!-- Start Container-->
<div class="container-detail-no-login">
    <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), home_path  %>
        </div>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <% if current_user %>
        <% else %>
        <div class="site-nav-3">
            <%= link_to "Sign Up", signup_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Log In", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "About" , about_path %>
        </div>
        <% end %>
        <% if current_user%>
        <% if current_user.email == 'admin'%>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Edit", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Admin Order", orders_path %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% else %>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "User Order", userorder_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% end %>
        <% end %>
    </div>
    <!-- Start Images Content 1 -->
    <div class="site-images-1">
        <%= image_tag("hood1.jpg")%>
    </div>
    <!-- End Images Content 1 -->
    <!-- Start detail -->
    <div class="detail link-color">
        <p style="font-size: 2em">black chenille sweatshirt</p>
        <p style="font-size: 1.5em">Featuring romantic mottos that have become synonymous with the House, a Gucci "Maison de l'Amour" and "Sine Amore Nihil" embroidery decorates the front of this black chenille sweatshirt, designed with short sleeves and tonal acetate trims. Influences drawn from the sportswear and leisurewear worlds collide into an inherently Gucci style juxtaposing athletic inspired shapes with soft, refined fabrics.

        Black cotton chenille
        Black acetate trims
        Gucci "Maison de l'Amour" and "Sine Amore Nihil" embroidery
        Crewneck
        Short sleeves
        Knit rib trims
        85% cotton and 15% polyamide
        Made in Italy
        The model is 6' and is wearing size small</p>
        <% if current_user %>
        <%= link_to ">> Buy Now <<" , neworder_path %>
        <% else %>
        <%= link_to ">> Buy Now <<" , neworderfalse_path %>
        <% end %>
    </div>
    <!-- End detail -->
    <div class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </div>
</div>
<!-- End Container-->

app/views/detail_no_login/index4.html.erb
<!-- Start Container-->
<div class="container-detail-no-login">
    <div class="site-header">
        <div class="site-logo">
            <%= link_to image_tag("logo.png",width:'250',height:'70'), home_path  %>
        </div>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <% if current_user %>
        <% else %>
        <div class="site-nav-3">
            <%= link_to "Sign Up", signup_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Log In", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "About" , about_path %>
        </div>
        <% end %>
        <% if current_user%>
        <% if current_user.email == 'admin'%>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "Edit", login_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Admin Order", orders_path %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% else %>
        <div class="site-nav-2">
            <%= link_to "Home" , home_path %>
        </div>
        <div class="site-nav-3">
            <%= link_to "About" , about_path %>
        </div>
        <div class="site-nav-4">
            <%= link_to "User Order", userorder_path %>
        </div>
        <div class="site-nav-5">
            <%= link_to "Edit", edit_user_path(current_user) %>
        </div>
        <div class="site-nav-6">
            <%= link_to "Log Out", logout_path %>
        </div>
        <% end %>
        <% end %>
    </div>
    <!-- Start Images Content 1 -->
    <div class="site-images-1">
         <%= image_tag("hood3.jpg")%>
    </div>
    <!-- End Images Content 1 -->
    <!-- Start detail -->
    <div class="detail link-color">
       
        <p style="font-size: 2em">black chenille sweatshirt</p>
        <p style="font-size: 1.5em">Featuring romantic mottos that have become synonymous with the House, a Gucci "Maison de l'Amour" and "Sine Amore Nihil" embroidery decorates the front of this black chenille sweatshirt, designed with short sleeves and tonal acetate trims. Influences drawn from the sportswear and leisurewear worlds collide into an inherently Gucci style juxtaposing athletic inspired shapes with soft, refined fabrics.

        Black cotton chenille
        Black acetate trims
        Gucci "Maison de l'Amour" and "Sine Amore Nihil" embroidery
        Crewneck
        Short sleeves
        Knit rib trims
        85% cotton and 15% polyamide
        Made in Italy
        The model is 6' and is wearing size small</p>
        <% if current_user %>
        <%= link_to ">> Buy Now <<" , neworder_path %>
        <% else %>
        <%= link_to ">> Buy Now <<" , neworderfalse_path %>
        <% end %>
    </div>
    <!-- End detail -->
    <div class="site-footer">
        <p style="text-align: center">&copy; <b>2019 - CN340 SOFTWARE ENGINEERING</b></p>
    </div>
</div>
<!-- End Container-->